// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cinema.Data;

#nullable disable

namespace cinema.Migrations
{
    [DbContext(typeof(CinemaContext))]
    partial class CinemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("cinema.Models.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTicketsSold")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SalonId");

                    b.ToTable("Displays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            SalonId = 2,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            SalonId = 1,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 3,
                            SalonId = 1,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 4,
                            SalonId = 2,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 3,
                            SalonId = 2,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 5,
                            SalonId = 1,
                            TicketsSold = 0,
                            Time = new DateTime(2021, 12, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalTicketsSold = 0
                        });
                });

            modelBuilder.Entity("cinema.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Jumanji"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Birds of Prey"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Frozen 2"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Mulan"
                        },
                        new
                        {
                            Id = 5,
                            Title = "1917"
                        });
                });

            modelBuilder.Entity("cinema.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Salon 1",
                            Seats = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Salon 2",
                            Seats = 100
                        });
                });

            modelBuilder.Entity("cinema.Models.Display", b =>
                {
                    b.HasOne("cinema.Models.Movie", "Movie")
                        .WithMany("Displays")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinema.Models.Salon", "Salon")
                        .WithMany("Displays")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("cinema.Models.Movie", b =>
                {
                    b.Navigation("Displays");
                });

            modelBuilder.Entity("cinema.Models.Salon", b =>
                {
                    b.Navigation("Displays");
                });
#pragma warning restore 612, 618
        }
    }
}
